SecRuleRemoveById 920350
SecRule REQUEST_URI "@beginsWith /healthz" \
    "id:1001,phase:1,pass,nolog,noauditlog,ctl:ruleEngine=Off"

#CSRF Payment-CVE-2023-6671
SecRule REQUEST_METHOD "@streq POST" \
    "id:1000101,\
    phase:2,\
    pass,\
    log,\
    msg:'CAPSTONE CSRF Test - OJS Payment savePaymentTypes',\
    tag:'capstone',\
    tag:'attack-csrf',\
    tag:'ojs',\
    tag:'cve-2023-6671',\
    chain"
    SecRule REQUEST_URI "@contains /index.php/OJS/payments/savePaymentTypes"

#Arbitary PHP-like File Upload via Native XML Import-CVE-2023-47271
SecRule REQUEST_BODY "@rx (?i)([a-z0-9_\-./]+?\.(?:php|phtml|phar|php[0-9]?|pht))\b" \
    "id:1000201,\
    phase:2,\
    pass,\
    log,\
    capture,\
    msg:'CAPSTONE - CVE-2023-47271 Suspicious Executable File Upload Attempt. Payload=%{TX.0}',\
    severity:'WARNING',\
    tag:'capstone',\
    tag:'cve-2023-47271',\
    tag:'ojs',\
    tag:'attack-file-upload',\
    tag:'possible-rce'"

#Accsess uploaded file
SecRule REQUEST_URI "@rx (?i)^(/public/journals/[0-9]+/[^?]+\.(?:php|phtml|phar|php[0-9]?|pht))(?:\?.*)?$" \
    "id:1000202,\
    phase:1,\
    pass,\
    log,\
    capture,\
    msg:'CAPSTONE - CVE-2023-47271 Uploaded Executable File Accessed. URI=%{TX.0}',\
    severity:'CRITICAL',\
    tag:'capstone',\
    tag:'cve-2023-47271',\
    tag:'ojs',\
    tag:'attack-rce',\
    tag:'php-execution-attempt'"

#RCE
SecRule REQUEST_URI "@rx (?i)^/public/journals/[0-9]+/[^?]+\.(?:php|phtml|phar|php[0-9]?|pht)(?:\?.*)?$" \
    "id:1000204,\
    phase:4,\
    pass,\
    log,\
    capture,\
    msg:'CAPSTONE - CVE-2023-47271 Possible RCE Confirmed. Indicator=%{TX.0}',\
    severity:'CRITICAL',\
    tag:'capstone',\
    tag:'cve-2023-47271',\
    tag:'ojs',\
    tag:'attack-rce',\
    tag:'php-execution-confirmed',\
    chain"
    SecRule RESPONSE_BODY "@rx (?i)(uid=[0-9]+\(.*?\)|gid=[0-9]+\(.*?\)|php\s+version|document_root|server_addr|server_software|loaded configuration file|disable_functions|www-data|apache|nginx)"
